<?php

    namespace Ehven\Gilad\WordPress\Themes\Parents\TypeEight;

    if ( ! defined( 'ABSPATH' ) ) exit( 'Nothing to see here. Go <a href="/">home</a>.' );

    require_once( TYPE8_CORE_DOCUMENT . '/attachment.php' );

    class Template_Attachment extends CORE_Attachment {

        public function __construct() {

            parent::__construct();

        }

    }

    $template_attachment = new Template_Attachment();
    $data = get_object_vars( $template_attachment );

    $template_attachment->dump( $data );


    get_header();

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - //

    $view_file = get_stylesheet_directory() . '/view-attachment.php';

    if ( file_exists( $view_file ) ) {

        require_once( $view_file );

    } else {

        echo '<div class="col-12">';
        echo '<h1>This is an Attachment page</h1>';
        echo '<h3>Generated by the <code>attachment.php</code> template</h3>';
        echo '</div>';

    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - //

    if ( comments_open() || get_comments_number() ) {

        comments_template();

    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - //

    get_footer();
