<?php

    namespace Ehven\Gilad\WordPress\Themes\Parents\TypeEight;

    if ( ! defined( 'ABSPATH' ) ) exit( 'Nothing to see here. Go <a href="/">home</a>.' );

    require_once( TYPE8_CORE_DOCUMENT . '/audio.php' );

    class Template_Audio extends CORE_Audio {

        public function __construct() {

            parent::__construct();

        }

    }

    $template_audio = new Template_Audio();
    $data = get_object_vars( $template_audio );

    $template_audio->dump( $data );

    ?>

<h1>This is an Audio post</h1>
<h3>Generated by the <code>audio.php</code> template</h3>
