<?php

    namespace Ehven\Gilad\WordPress\Themes\Parents\TypeEight;

    if ( ! defined( 'ABSPATH' ) ) exit( 'Nothing to see here. Go <a href="/">home</a>.' );

    require_once( TYPE8_CORE_LIST . '/author.php' );

    class Template_Author extends CORE_Author {

        public function __construct() {

            parent::__construct();

        }

    }

    $template_author = new Template_Author();
    $data = get_object_vars( $template_author );

    $template_author->dump( $data );

    ?>

<h1>This is an Author page</h1>
<h3>Generated by the <code>author.php</code> template</h3>
