<?php

    namespace Ehven\Gilad\WordPress\Themes\Parents\TypeEight;

    if ( ! defined( 'ABSPATH' ) ) exit( 'Nothing to see here. Go <a href="/">home</a>.' );

    require_once( TYPE8_CORE_FRONT . '/home.php' );

    class Template_Home extends CORE_Home {

        public function __construct() {

            parent::__construct();

        }

    }

    $template_home = new Template_Home();
    $data = get_object_vars( $template_home );

    $template_home->dump( $data );

    ?>

<h1>This is the Home page</h1>
<h3>Generated by the <code>home.php</code> template</h3>
