<?php

    namespace Ehven\Gilad\WordPress\Themes\Parents\TypeEight;

    if ( ! defined( 'ABSPATH' ) ) exit( 'Nothing to see here. Go <a href="/">home</a>.' );

    require_once( TYPE8_CORE_DOCUMENT . '/image.php' );

    class Template_Image extends CORE_Image {

        public function __construct() {

            parent::__construct();

        }

    }

    $template_image = new Template_Image();
    $data = get_object_vars( $template_image );

    $template_image->dump( $data );

    get_header();

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - //

    $view_file = get_stylesheet_directory() . '/view-image.php';

    if ( file_exists( $view_file ) ) {

        require_once( $view_file );

    } else {

        echo '<div class="col-12">';
        echo '<h1>This is an Image page</h1>';
        echo '<h3>Generated by the <code>image.php</code> template</h3>';
        echo '</div>';

    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - //

    if ( comments_open() || get_comments_number() ) {

        comments_template();

    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - //

    get_footer();
