<?php

    namespace Ehven\Gilad\WordPress\Themes\Parents\TypeEight;

    if ( ! defined( 'ABSPATH' ) ) exit( 'Nothing to see here. Go <a href="/">home</a>.' );

    require_once( TYPE8_CORE_LIST . '/index.php' );

    class Template_Index extends CORE_Index {

        public function __construct() {

            parent::__construct();

        }

    }

    $template_index = new Template_Index();
    $data = get_object_vars( $template_index );

    $template_index->dump( $data );

    ?>

<h1>This is the Index page</h1>
<h3>Generated by the <code>index.php</code> template</h3>
