<?php

    namespace Ehven\Gilad\WordPress\Themes\Parents\TypeEight;

    if ( ! defined( 'ABSPATH' ) ) exit( 'Nothing to see here. Go <a href="/">home</a>.' );

    require_once( TYPE8_CORE_DOCUMENT . '/page.php' );

    class Template_Page extends CORE_Page {

        public function __construct() {

            parent::__construct();

        }

    }

    $template_page = new Template_Page();
    $data = get_object_vars( $template_page );

    $template_page->dump( $data );

    ?>

<h1>This is a Page</h1>
<h3>Generated by the <code>page.php</code> template</h3>
