<?php

    namespace Ehven\Gilad\WordPress\Themes\Parents\TypeEight;

    if ( ! defined( 'ABSPATH' ) ) exit( 'Nothing to see here. Go <a href="/">home</a>.' );

    require_once( TYPE8_CORE_LIST . '/search.php' );

    class Template_Search extends CORE_Search {

        public function __construct() {

            parent::__construct();

        }

    }

    $template_search = new Template_Search();
    $data = get_object_vars( $template_search );

    $template_search->dump( $data );

    ?>

<h1>This is a Search Results page</h1>
<h3>Generated by the <code>search.php</code> template</h3>
