<?php

    namespace Ehven\Gilad\WordPress\Themes\Parents\TypeEight;

    if ( ! defined( 'ABSPATH' ) ) exit( 'Nothing to see here. Go <a href="/">home</a>.' );

    require_once( TYPE8_CORE_DOCUMENT . '/single.php' );

    class Template_Single extends CORE_Single {

        public function __construct() {

            parent::__construct();

        }

    }

    $template_single = new Template_Single();
    $data = get_object_vars( $template_single );

    $template_single->dump( $data );

    get_header();

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - //

    $php_view_file = get_stylesheet_directory() . '/view-' . $data['document_template'] . '.php';

    if ( file_exists( $php_view_file ) ) {

        require_once( TYPE8_UTILITIES );
        require_once( $php_view_file );

    } else {

        echo '<div class="col-12">';
        echo '<h1>This is a ' . ucwords( $data['document_template'] ) . ' page</h1>';
        echo '<h3>Generated by the <code>' . strtolower( $data['document_template'] ) . '.php</code> template</h3>';
        echo '</div>';

    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - //

    if ( comments_open() || get_comments_number() ) {

        comments_template();

    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - //

    get_footer();
