<?php

    namespace Ehven\Gilad\WordPress\Themes\Parents\TypeEight;

    if ( ! defined( 'ABSPATH' ) ) exit( 'Nothing to see here. Go <a href="/">home</a>.' );

    require_once( TYPE8_CORE_LIST . '/taxonomy.php' );

    class Template_Taxonomy extends CORE_Taxonomy {

        public function __construct() {

            parent::__construct();

        }

    }

    $template_taxonomy = new Template_Taxonomy();
    $data = get_object_vars( $template_taxonomy );

    $template_taxonomy->dump( $data );

    ?>

<h1>This is a Taxonomy page</h1>
<h3>Generated by the <code>taxonomy.php</code> template</h3>
